import { useState, type FormEvent } from 'react'
import { ArrowRight, GraduationCap, LockKeyhole, Mail } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { Button, Field } from '../components/ui'
import { supabase } from '../lib/supabase/client'
import { friendlyError } from '../utils/errors'

function AuthFrame({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <main className="auth-page"><section className="auth-aside"><div className="brand brand-light"><span className="brand-mark"><GraduationCap size={21}/></span>Companion<span>Study</span></div><div><p className="eyebrow">TU COMPAÑERO DE ESTUDIO</p><h1>Estudiá con un plan. Avanzá acompañado.</h1><p>Organizá tus materias, preparate con IA y celebrá cada progreso junto a tu mascota.</p></div><div className="auth-quote">“Las metas grandes se construyen con sesiones pequeñas y constantes.”</div></section><section className="auth-form-wrap"><div className="auth-form"><Link className="mobile-brand" to="/"><span className="brand-mark"><GraduationCap size={20}/></span>CompanionStudy</Link><p className="eyebrow">BIENVENIDO</p><h2>{title}</h2><p className="muted">{subtitle}</p>{children}</div></section></main> }
function Message({ text, success = false }: { text: string; success?: boolean }) { return <p className={success ? 'form-success' : 'form-error'} role="alert">{text}</p> }

export function LoginPage() { const navigate = useNavigate(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); setLoading(true); const { error: loginError } = await supabase.auth.signInWithPassword({ email, password }); setLoading(false); if (loginError) { setError(friendlyError(loginError)); return } navigate('/app') }
  return <AuthFrame title="Qué bueno verte" subtitle="Ingresá para continuar con tu plan de hoy."><form onSubmit={submit}><Field label="Email"><span className="input-with-icon"><Mail size={18}/><input type="email" autoComplete="email" required value={email} onChange={(e) => setEmail(e.target.value)} placeholder="vos@ejemplo.com"/></span></Field><Field label="Contraseña"><span className="input-with-icon"><LockKeyhole size={18}/><input type="password" autoComplete="current-password" required minLength={8} value={password} onChange={(e) => setPassword(e.target.value)} placeholder="••••••••"/></span></Field><Link className="forgot-link" to="/forgot-password">¿Olvidaste tu contraseña?</Link>{error && <Message text={error}/>}<Button className="button-primary full" type="submit" loading={loading}>Ingresar <ArrowRight size={18}/></Button></form><p className="auth-switch">¿Todavía no tenés cuenta? <Link to="/register">Crear cuenta</Link></p></AuthFrame> }

export function RegisterPage() { const navigate = useNavigate(); const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [loading, setLoading] = useState(false)
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); setNotice(''); setLoading(true); const { data, error: signUpError } = await supabase.auth.signUp({ email, password, options: { data: { display_name: name }, emailRedirectTo: `${window.location.origin}/login` } }); setLoading(false); if (signUpError) { setError(friendlyError(signUpError)); return } if (!data.session) { setNotice('Revisá tu email para confirmar la cuenta y luego iniciá sesión.'); return } navigate('/onboarding') }
  return <AuthFrame title="Creá tu espacio" subtitle="Tu información académica queda privada y vinculada a tu cuenta."><form onSubmit={submit}><Field label="¿Cómo querés que te llamemos?"><input required maxLength={60} value={name} onChange={(e) => setName(e.target.value)} placeholder="Tu nombre"/></Field><Field label="Email"><input type="email" autoComplete="email" required value={email} onChange={(e) => setEmail(e.target.value)} placeholder="vos@ejemplo.com"/></Field><Field label="Contraseña"><input type="password" autoComplete="new-password" required minLength={8} value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Mínimo 8 caracteres"/></Field>{error && <Message text={error}/>} {notice && <Message text={notice} success/>}<Button className="button-primary full" type="submit" loading={loading}>Crear mi cuenta <ArrowRight size={18}/></Button></form><p className="auth-switch">¿Ya tenés cuenta? <Link to="/login">Ingresar</Link></p></AuthFrame> }

export function ForgotPasswordPage() { const [email, setEmail] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); setLoading(true); const { error: resetError } = await supabase.auth.resetPasswordForEmail(email, { redirectTo: `${window.location.origin}/reset-password` }); setLoading(false); if (resetError) setError(friendlyError(resetError)); else setMessage('Si existe una cuenta con ese email, te enviamos un enlace para recuperar tu contraseña.') }
  return <AuthFrame title="Recuperá tu acceso" subtitle="Te enviamos un enlace seguro para elegir una contraseña nueva."><form onSubmit={submit}><Field label="Email"><input type="email" required value={email} onChange={(e) => setEmail(e.target.value)} placeholder="vos@ejemplo.com"/></Field>{error && <Message text={error}/>} {message && <Message text={message} success/>}<Button className="button-primary full" type="submit" loading={loading}>Enviar enlace</Button></form><p className="auth-switch"><Link to="/login">Volver a ingresar</Link></p></AuthFrame> }

export function ResetPasswordPage() { const navigate = useNavigate(); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(false); const submit = async (event: FormEvent) => { event.preventDefault(); setLoading(true); setError(''); const { error: updateError } = await supabase.auth.updateUser({ password }); setLoading(false); if (updateError) setError(friendlyError(updateError)); else { setMessage('Contraseña actualizada. Ya podés ingresar.'); window.setTimeout(() => navigate('/app'), 800) } }; return <AuthFrame title="Nueva contraseña" subtitle="Elegí una contraseña segura de al menos 8 caracteres."><form onSubmit={submit}><Field label="Contraseña nueva"><input type="password" required minLength={8} autoComplete="new-password" value={password} onChange={(e) => setPassword(e.target.value)}/></Field>{error && <Message text={error}/>} {message && <Message text={message} success/>}<Button className="button-primary full" loading={loading}>Guardar contraseña</Button></form></AuthFrame> }
