import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react'
import { ChevronLeft, ChevronRight, Plus, Trash2 } from 'lucide-react'
import { Button, Card, EmptyState, ErrorState, Field, LoadingBlock, Modal } from '../components/ui'
import { useAuth } from '../features/auth/AuthProvider'
import { eventsApi, subjectsApi } from '../services/api'
import type { CalendarEvent, Subject } from '../types/domain'
import { friendlyError } from '../utils/errors'

type View = 'month' | 'day' | 'agenda'
const startOfMonth = (date: Date) => new Date(date.getFullYear(), date.getMonth(), 1)
export function CalendarPage() { const { user } = useAuth(); const [cursor, setCursor] = useState(startOfMonth(new Date())); const [view, setView] = useState<View>('month'); const [events, setEvents] = useState<CalendarEvent[]>([]); const [subjects, setSubjects] = useState<Subject[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [adding, setAdding] = useState(false)
  const range = useMemo(() => { const start = new Date(cursor.getFullYear(), cursor.getMonth(), 1); const end = new Date(cursor.getFullYear(), cursor.getMonth() + 1, 1); return { start, end } }, [cursor])
  const load = useCallback(async () => { setLoading(true); try { setError(''); const [eventRows, subjectRows] = await Promise.all([eventsApi.list(range.start.toISOString(), range.end.toISOString()), subjectsApi.list()]); setEvents(eventRows); setSubjects(subjectRows) } catch (err) { setError(friendlyError(err)) } finally { setLoading(false) } }, [range.end, range.start])
  useEffect(() => { void load() }, [load])
  const move = (amount: number) => setCursor((date) => new Date(date.getFullYear(), date.getMonth() + amount, 1))
  if (!user) return <div className="page"><LoadingBlock/></div>
  return <div className="page calendar-page"><header className="page-heading"><div><p className="eyebrow">PLANIFICACIÓN</p><h1>Calendario</h1><p>Un panorama claro de clases, tareas y momentos de estudio.</p></div><Button className="button-primary" onClick={() => setAdding(true)}><Plus size={17}/> Nuevo evento</Button></header><section className="calendar-toolbar"><div className="calendar-switch" role="tablist">{(['month', 'day', 'agenda'] as View[]).map((item) => <button key={item} className={view === item ? 'active' : ''} onClick={() => setView(item)}>{item === 'month' ? 'Mes' : item === 'day' ? 'Día' : 'Agenda'}</button>)}</div><div className="month-nav"><button className="icon-button" onClick={() => move(-1)} aria-label="Mes anterior"><ChevronLeft size={19}/></button><strong>{new Intl.DateTimeFormat('es-AR', { month: 'long', year: 'numeric' }).format(cursor)}</strong><button className="icon-button" onClick={() => move(1)} aria-label="Mes siguiente"><ChevronRight size={19}/></button></div></section>{error && <ErrorState message={error} retry={() => void load()}/>} {loading ? <LoadingBlock label="Cargando calendario..."/> : view === 'month' ? <MonthView cursor={cursor} events={events}/> : <AgendaView events={events} day={view === 'day' ? new Date() : undefined} onDelete={(id) => { if (window.confirm('¿Eliminar evento?')) void eventsApi.remove(id).then(load).catch((err) => setError(friendlyError(err))) }}/>} {adding && <EventForm userId={user.id} subjects={subjects} close={() => setAdding(false)} reload={load}/>}</div>
}
function MonthView({ cursor, events }: { cursor: Date; events: CalendarEvent[] }) { const cells = useMemo(() => { const first = new Date(cursor.getFullYear(), cursor.getMonth(), 1); const offset = (first.getDay() + 6) % 7; const start = new Date(first); start.setDate(first.getDate() - offset); return Array.from({ length: 42 }, (_, index) => { const date = new Date(start); date.setDate(start.getDate() + index); return date }) }, [cursor]); const eventMap = useMemo(() => new Map(cells.map((date) => [date.toDateString(), events.filter((event) => new Date(event.starts_at).toDateString() === date.toDateString())])), [cells, events]); return <Card className="month-calendar"><div className="weekday-row">{['Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb', 'Dom'].map((day) => <span key={day}>{day}</span>)}</div><div className="calendar-grid">{cells.map((date) => { const dayEvents = eventMap.get(date.toDateString()) ?? []; const isToday = date.toDateString() === new Date().toDateString(); return <div className={`calendar-cell ${date.getMonth() !== cursor.getMonth() ? 'outside' : ''} ${isToday ? 'today' : ''}`} key={date.toISOString()}><span>{date.getDate()}</span>{dayEvents.slice(0, 2).map((event) => <div className="calendar-event" title={event.title} key={event.id} style={{ borderColor: event.subjects?.color ?? '#7c6cff' }}>{event.title}</div>)}{dayEvents.length > 2 && <small>+{dayEvents.length - 2} más</small>}</div> })}</div></Card> }
function AgendaView({ events, day, onDelete }: { events: CalendarEvent[]; day?: Date; onDelete: (id: string) => void }) { const visible = day ? events.filter((event) => new Date(event.starts_at).toDateString() === day.toDateString()) : events; return visible.length ? <div className="agenda-list">{visible.map((event) => <Card className="agenda-event" key={event.id}><div><strong>{new Intl.DateTimeFormat('es-AR', { day: 'numeric', month: 'short' }).format(new Date(event.starts_at))}</strong><span>{new Intl.DateTimeFormat('es-AR', { hour: '2-digit', minute: '2-digit' }).format(new Date(event.starts_at))}</span></div><i style={{ background: event.subjects?.color ?? '#7c6cff' }}/><section><h3>{event.title}</h3><p>{event.subjects?.name ?? event.event_type} · {event.duration_minutes} min</p></section><button className="icon-button" aria-label={`Eliminar ${event.title}`} onClick={() => onDelete(event.id)}><Trash2 size={16}/></button></Card>)}</div> : <EmptyState title="No hay eventos en este período" description="Agregá una clase, un recordatorio o una sesión para armar tu agenda."/> }
function EventForm({ userId, subjects, close, reload }: { userId: string; subjects: Subject[]; close: () => void; reload: () => Promise<void> }) { const [title, setTitle] = useState(''); const [type, setType] = useState<CalendarEvent['event_type']>('study'); const [subjectId, setSubjectId] = useState(''); const [startsAt, setStartsAt] = useState(new Date().toISOString().slice(0, 16)); const [duration, setDuration] = useState('60'); const [saving, setSaving] = useState(false); const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); try { await eventsApi.create(userId, { title, event_type: type, subject_id: subjectId || null, starts_at: new Date(startsAt).toISOString(), duration_minutes: Number(duration), reminder_minutes: null, notes: null }); await reload(); close() } finally { setSaving(false) } }; return <Modal title="Nuevo evento" onClose={close}><form className="modal-form" onSubmit={(event) => void submit(event)}><Field label="Título"><input required autoFocus maxLength={180} value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Ej. Repasar unidades 1 y 2"/></Field><div className="field-grid"><Field label="Tipo"><select value={type} onChange={(event) => setType(event.target.value as CalendarEvent['event_type'])}><option value="study">Estudio</option><option value="class">Clase</option><option value="exam">Evaluación</option><option value="task">Tarea</option><option value="reminder">Recordatorio</option><option value="other">Otro</option></select></Field><Field label="Materia"><select value={subjectId} onChange={(event) => setSubjectId(event.target.value)}><option value="">Sin materia</option>{subjects.map((subject) => <option key={subject.id} value={subject.id}>{subject.name}</option>)}</select></Field></div><Field label="Inicio"><input type="datetime-local" required value={startsAt} onChange={(event) => setStartsAt(event.target.value)}/></Field><Field label="Duración (minutos)"><input type="number" min="5" max="1440" required value={duration} onChange={(event) => setDuration(event.target.value)}/></Field><div className="modal-actions"><Button className="button-primary" type="submit" loading={saving}>Guardar evento</Button></div></form></Modal> }
