import { useCallback, useEffect, useState } from 'react'
import { ArrowRight, BookOpen, CalendarDays, Clock3, Flame, Sparkles, Target, Trophy } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { Button, Card, EmptyState, ErrorState, LoadingBlock } from '../components/ui'
import { appApi } from '../services/api'
import type { DashboardData } from '../types/domain'
import { friendlyError } from '../utils/errors'

const greeting = () => { const hour = new Date().getHours(); return hour < 12 ? 'Buenos días' : hour < 19 ? 'Buenas tardes' : 'Buenas noches' }
const dateLabel = new Intl.DateTimeFormat('es-AR', { weekday: 'long', day: 'numeric', month: 'long' })
export function DashboardPage() { const [data, setData] = useState<DashboardData | null>(null); const [error, setError] = useState(''); const navigate = useNavigate()
  const load = useCallback(async () => { setError(''); try { const result = await appApi.dashboard(); if (!result.profile?.onboarding_completed) { navigate('/onboarding', { replace: true }); return } setData(result) } catch (err) { setError(friendlyError(err)) } }, [navigate])
  useEffect(() => { void load() }, [load])
  if (error) return <div className="page"><ErrorState message={error} retry={() => void load()}/></div>
  if (!data) return <div className="page"><LoadingBlock label="Armando tu plan de hoy..."/></div>
  const levelProgress = data.level.next_level ? Math.min(100, ((data.level.xp - data.level.min_xp) / (data.level.next_level.min_xp - data.level.min_xp)) * 100) : 100
  return <div className="page dashboard"><header className="page-heading"><div><p className="eyebrow">{dateLabel.format(new Date())}</p><h1>{greeting()}{data.profile?.display_name ? `, ${data.profile.display_name}` : ''}.</h1><p>Un paso a la vez. Hoy podés avanzar mucho.</p></div><Button className="button-primary desktop-action" onClick={() => navigate('/app/study')}><Sparkles size={17}/> Estudiar con IA</Button></header>
    <section className="hero-grid"><Card className="focus-card"><div className="card-kicker"><Target size={17}/> PRÓXIMO FOCO</div>{data.recommendation ? <><h2>{data.recommendation.subject_name ?? 'Tu próximo paso'}</h2><p className="focus-topic">{data.recommendation.topic}</p><p>{data.recommendation.reason}</p><div className="focus-footer"><span><Clock3 size={16}/>{data.recommendation.duration_minutes} min</span><Button className="button-secondary" onClick={() => navigate(`/app/study${data.recommendation?.subject_id ? `?subject=${data.recommendation.subject_id}` : ''}`)}>{data.recommendation.action}<ArrowRight size={16}/></Button></div></> : <><h2>Empezá con una sesión breve</h2><p>Agregá una tarea, una evaluación o elegí una materia para que armemos recomendaciones basadas en tus datos.</p><Button className="button-secondary" onClick={() => navigate('/app/subjects')}>Crear mi primera materia <ArrowRight size={16}/></Button></>}</Card>
      <Card className="pet-glance"><div><p className="card-kicker">TU COMPAÑERO</p>{data.pet ? <><h2>{data.pet.name}</h2><p>{data.pet.happiness >= 70 ? 'Está feliz de estudiar con vos.' : 'Necesita un poco de atención.'}</p><div className="pet-meter"><span>Felicidad</span><strong>{data.pet.happiness}%</strong><div><i style={{ width: `${data.pet.happiness}%` }}/></div></div><button className="text-button" onClick={() => navigate('/app/pet')}>Cuidar a {data.pet.name}</button></> : <><h2>Tu mascota te espera</h2><p>Elegila para tener un compañero de progreso.</p></>}</div><div className="pixel-pet" aria-label={data.pet ? `Mascota ${data.pet.name}` : 'Mascota'} role="img">{data.pet?.species === 'owl' ? '🦉' : data.pet?.species === 'fox' ? '🦊' : data.pet?.species === 'dog' ? '🐶' : '🐱'}</div></Card></section>
    <section className="progress-row"><Card><Flame className="metric-icon flame"/><div><strong>{data.streak.current_streak} días</strong><span>racha actual</span></div></Card><Card><Trophy className="metric-icon gold"/><div><strong>{data.level.xp} XP</strong><span>Nivel {data.level.id} · {data.level.name}</span></div><div className="tiny-progress"><i style={{ width: `${Math.max(4, levelProgress)}%` }}/></div></Card><Card><BookOpen className="metric-icon purple"/><div><strong>{data.today.study_sessions.length}</strong><span>sesiones hoy</span></div></Card></section>
    <div className="dashboard-columns"><section><div className="section-title"><div><h2>Hoy</h2><p>Lo que te acerca a tus objetivos.</p></div><button className="text-button" onClick={() => navigate('/app/calendar')}>Ver calendario</button></div><Card className="today-list">{data.today.tasks.length || data.today.events.length ? <>{data.today.tasks.map((task) => <button className="list-row" key={task.id} onClick={() => navigate('/app/more')}><span className="check-circle"/><span><strong>{task.title}</strong><small>{task.subjects?.name ?? 'Sin materia'} {task.due_at ? `· ${new Intl.DateTimeFormat('es-AR', { hour: '2-digit', minute: '2-digit' }).format(new Date(task.due_at))}` : ''}</small></span><ArrowRight size={17}/></button>)}{data.today.events.map((event) => <div className="list-row" key={event.id}><CalendarDays size={18}/><span><strong>{event.title}</strong><small>{event.subjects?.name ?? event.event_type} · {new Intl.DateTimeFormat('es-AR', { hour: '2-digit', minute: '2-digit' }).format(new Date(event.starts_at))}</small></span></div>)}</> : <EmptyState title="Tu día está despejado" description="Creá una tarea o evento para convertir tu plan en acción." action={<Button className="button-secondary" onClick={() => navigate('/app/more')}>Agregar tarea</Button>}/>}</Card></section>
      <section><div className="section-title"><div><h2>Evaluaciones cercanas</h2><p>Prepará lo importante antes.</p></div></div><Card className="exam-list">{data.upcoming_exams.length ? data.upcoming_exams.map((exam) => <div className="exam-row" key={exam.id}><div className="date-chip"><strong>{exam.scheduled_at ? new Date(exam.scheduled_at).getDate() : '—'}</strong><span>{exam.scheduled_at ? new Intl.DateTimeFormat('es-AR', { month: 'short' }).format(new Date(exam.scheduled_at)) : ''}</span></div><div><strong>{exam.title}</strong><p>{exam.subjects?.name ?? 'Sin materia'}</p></div><button className="icon-button" aria-label={`Prepararme para ${exam.title}`} onClick={() => navigate(`/app/study${exam.subject_id ? `?subject=${exam.subject_id}` : ''}`)}><Sparkles size={17}/></button></div>) : <EmptyState title="Sin evaluaciones próximas" description="Cuando registres una, aparecerá tu mejor momento para prepararte."/>}</Card></section></div><Button className="button-primary mobile-study" onClick={() => navigate('/app/study')}><Sparkles size={17}/> Estudiar con IA</Button></div>
}
