import { useCallback, useEffect, useState, type ReactNode } from 'react'
import { BatteryCharging, Cookie, Heart, Play, Sparkles, Sun } from 'lucide-react'
import { Button, Card, EmptyState, ErrorState, LoadingBlock } from '../components/ui'
import { appApi } from '../services/api'
import type { Pet } from '../types/domain'
import { friendlyError } from '../utils/errors'

export function PetPage() { const [pet, setPet] = useState<Pet | null>(null); const [reaction, setReaction] = useState(''); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const load = useCallback(async () => { setLoading(true); try { const dashboard = await appApi.dashboard(); setPet(dashboard.pet) } catch (err) { setError(friendlyError(err)) } finally { setLoading(false) } }, []); useEffect(() => { void load() }, [load]); const care = async (action: 'feed' | 'play' | 'rest') => { setBusy(true); setError(''); try { const data = await appApi.petCare(action); setPet(data.pet); setReaction(data.reaction) } catch (err) { setError(friendlyError(err, 'No pudimos cuidar a tu mascota. Intentá nuevamente.')) } finally { setBusy(false) } }; if (loading) return <div className="page"><LoadingBlock label="Buscando a tu compañero..."/></div>; if (!pet) return <div className="page"><EmptyState title="Tu mascota todavía no está lista" description="Completá el onboarding para elegir a tu compañero de estudio."/></div>; const status = pet.energy < 25 ? 'cansada' : pet.happiness < 35 ? 'triste' : pet.happiness > 75 ? 'feliz' : 'normal'; return <div className="page pet-page"><header className="page-heading"><div><p className="eyebrow">TU COMPAÑERO</p><h1>{pet.name}</h1><p>Estado actual: <strong>{status}</strong>. Tus hábitos de estudio también le dan energía.</p></div></header>{error && <ErrorState message={error} retry={() => void load()}/>}<section className="pet-stage"><div className={`pet-scene ${status}`}><div className="scene-stars">✦ · ✦ · ✦</div><div className="pet-sprite" role="img" aria-label={`${pet.name}, mascota ${pet.species}`}>{pet.species === 'dog' ? '🐶' : pet.species === 'fox' ? '🦊' : pet.species === 'owl' ? '🦉' : '🐱'}</div><div className="pet-shadow"/></div><Card className="pet-detail"><div className="pet-name"><div><p className="eyebrow">NIVEL {pet.level}</p><h2>{pet.name}</h2></div><span>{status}</span></div><Meter icon={<Heart size={18}/>} label="Felicidad" value={pet.happiness} tone="pink"/><Meter icon={<BatteryCharging size={18}/>} label="Energía" value={pet.energy} tone="green"/>{reaction && <p className="pet-reaction" role="status">✦ {reaction}</p>}<div className="pet-care-actions"><Button className="button-secondary" disabled={busy} onClick={() => void care('feed')}><Cookie size={17}/> Alimentar</Button><Button className="button-secondary" disabled={busy || pet.energy < 8} onClick={() => void care('play')}><Play size={17}/> Jugar</Button><Button className="button-secondary" disabled={busy} onClick={() => void care('rest')}><Sun size={17}/> Descansar</Button></div><p className="pet-help"><Sparkles size={15}/> Completar tareas y quizzes también mejora su ánimo. No hay castigos: si te alejás, sólo va a necesitar que vuelvas.</p></Card></section></div> }
function Meter({ icon, label, value, tone }: { icon: ReactNode; label: string; value: number; tone: string }) { return <div className="pet-stat"><div><span className={tone}>{icon}</span><strong>{label}</strong><b>{value}%</b></div><div className="meter"><i className={tone} style={{ width: `${value}%` }}/></div></div> }
